"""Package, Skill, and data-contract versions."""

PACKAGE_VERSION = "0.3.0"
SKILL_VERSION = "0.3.0"
CORE_SCHEMA_VERSION = "0.1.0"
ANALYSIS_SCHEMA_VERSION = "0.2.0"
TEXT_ANALYSIS_SCHEMA_VERSION = "0.3.0"
